spring:
   datasource:
      url: jdbc:mysql://39.105.142.33:3306/HXDB?useUnicode=true&characterEncoding=UTF-8
      username: banksys
      password: sa26212835
      driver-class-name: com.mysql.jdbc.Driver

   redis:
      database: 0
      host: 39.105.142.33
      port: 6379
      password: sa26212835

   application:
      name: project-assets

server:
   port: 8771

eureka:
   client:
      serviceUrl:
         defaultZone: http://localhost:8661/eureka/

mybatis:
   mapper-locations: classpath:mapping/*/*Mapper.xml
   type-aliases-package: com.virugan.tables.*

